services:
  - type: web
    name: crypto-volatility-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn webapp:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
